### ISSUE TITLE
ImportError: No module named dj_database_url

### ISSUE THREAD

**Issue by prakashn27** [mjhea0/hibbert-django#1]
When i try to runserver i get the below error.

ImportError: No module named dj_database_url

**Comment by b3h3rkz** [comment]
Getting this same error. Still not fixed?

**Comment by prakashn27** [comment]
I had a workaround at that time. Forgot now. :confounded:

**Comment by monipodio** [comment]
prakashn27, you are an idiot. How you can give that answer
